sudo: required
dist: trusty

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

language: cpp

script:
#  - make
   - mkdir compiler-build
   - cd compiler-build
   - cmake .. || true
   - make || true
   - cmake .
   - make
   - ctest
