/*Code generation file, cpp file*/

/* WE NEED TO SLOWLY LOWER THE ABSTRACTION LEVEL SLOWLY, LIKE ONE STEP A TIME TO WRITE THIS PART, IT IS ALSO GOOD FOR DEBUG*/

/* AFTER CHECK THE SEMANTICS, THIS PART WILL BE USED*/

/*POSSIBLY THERE WILL BE SOME OPTIMIZATIONS BETWEEN SOME PASSES TO MAKE THE ENTIRE PROCESS BETTER*/


/* WE ALSO NEED TO ADD TETING METHOD FOR CODE GENERATION SO WE CAN TREAT BUG WISELY AND EFFECIENTLY*/

/* GUIDELINE OF CODE GENERATOR CPP ENDS HERE*/


